apiVersion: v1
kind: Pod
metadata:
  name: debug-mysqltest 
spec:
  containers:
  - name: mysqltest
    image: hub.pingcap.net/longroad/mysqltest:0.2
    env:
      - name: LONGROAD_DB_USER
        value: root
      - name: LONGROAD_DB_PASSWORD
        value: ""
      - name: LONGROAD_DB_HOST
        value: 172.16.4.61
      - name: LONGROAD_DB_PORT
        value: "31124"
      - name: LONGROAD_DB_NAME
        value: mysqltest
    command:
      - "/usr/local/bin/dumb-init"
      - "/mysql_test"
