apiVersion: v1
kind: Service
metadata:
  name: longroad
  labels:
    longroad: longroad
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32333
    name: longroad-http
  selector:
    longroad: longroad
