apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longroad
  labels:
    longroad: longroad
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longroad
subjects:
- kind: ServiceAccount
  name: longroad
  namespace: longroad
